service: rapBattleAPI

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getRandomRap:
    handler: controllers/getRap.handler
    events: 
      - http:
          path: rap/{keyword}
          method: get 
          cors: true
  postRapToTwitter:
    handler: controllers/postRapToTweet.handler
    events:
      - sns: arn:aws:sns:us-east-1:929569807000:tweet
