service: rapBattleAPI

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getRandomRap:
    handler: controllers/handler.getRap
    events: 
      - http:
          path: rap/{keyword}
          method: get 
          cors: true